name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kód letöltése
      uses: actions/checkout@v4

    - name: .NET SDK telepítése
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build futtatása
      run: dotnet build

    - name: Tesztek futtatása lefedettség méréssel
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Lefedettségi riport generálása
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator \
          -reports:**/coverage.cobertura.xml \
          -targetdir:coverage-report \
          -reporttypes:Html

    - name: Lefedettségi riport feltöltése artifactként
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report
